IdleLands/IdleLands

src/core/emitter-watchers.js
src/core/event-loop.js
src/core/game-state.js
src/plugins/chat/mute.socket.js
src/plugins/chat/sendmessage.socket.js
src/plugins/players/player.db.js
src/plugins/players/player.exists.socket.js
src/plugins/players/player.js
src/plugins/players/player.load.js
src/plugins/players/player.login.socket.js
src/plugins/players/player.movement.js
src/plugins/statistics/statistics.db.js
src/plugins/statistics/statistics.js
src/shared/di-wrapper.js
src/shared/playerlist-updater.js
test/core/base/character.spec.js
test/core/game-state.spec.js
test/plugins/players/player.movement.spec.js
test/plugins/players/player.spec.js

Dependency injection seems to work to my liking now.

Made global DI wrapper and added tests

---

test/client/client.js

adds a bunch of random names (bread, veg, deities), so we can now test
up to ~1200 players

Increase client player count

---

primus/server.js
src/plugins/combat/battle.js
src/shared/logger.js
test/client/client.js

Server alerts if quiet mode. Battle doesn’t output (even if in
BATTLE_DEBUG). Logger is quite (unless error). Test client alerts user,
doesn’t mention connections (at startup - still does otherwise). Also
cheekily random select of player names in test client. For yucks.

QUIET env flag

---

README.md

Added potential gotchya’s, the 3 other IL repos, explanations for the
.env file, a little more instruction on contributing, and some general
encouragement

fleshed out the readme

---

test/client/client.js

Jombocom comes first, by default (plus the other lot). —random
randomises the player selection. Plus a bunch of minor lint cleanups.

--random arg == random players, else ordered

---

src/shared/db-wrapper.js

Catches db close event, attempts re open. Logs if fails (if fail, not
sure what to do). Also tweaked MongoClient connection params, to try
better keep open (not convinced)

reopen db conn if it closes

---

primus/server.js

error handling on online url player count return. some embarrassing lint fixes.

fix online count return

---

scripts/restart-heroku.sh

script to restart heroku

---

src/plugins/achievements/achievements.db.js
src/plugins/collectibles/collectibles.db.js
src/plugins/personalities/personalities.db.js
src/plugins/players/player.db.js

Catches errors on mongodb.findOneAndUpdate, ignores them. Some comments
in there because we SHOULD come back and handle/test this properly.

err catch mongo findOneAndUpdate

---

src/plugins/players/player.db.js

Only one place, player.db, but catch/ignore. Can improve later.

Err catch mongodb.insertOne

---

README.md

Tips re debugging nodejs (based on convos in channel).

Add tips to readme

---

src/plugins/combat/battle.db.js

missed this from the general findOneAndUpdate err catch cleanup

err catch battledb.findOneAndUpdate

---

.gitignore

added to .gitignore. .keep file is just so git allows us to add the
empty dir

Create dist dir

---

src/plugins/statistics/statistics.db.js

missed this one from the general err catch, sorry.

add err catching to statistics save

---

src/plugins/combat/spells/Attack.js

Dropped weight from 40 to 30. minor, but should shift battles a little.
(heal & holy bolt at both weighted 40)

cleric more likely to cast

---

src/plugins/combat/spells/Berserk.js

Add spell description for Berserk

---

test/client/client.js

Pass in one of the names in the db. Makes it easier to, e.g. look at a specific class, for battle behaviour
etc

Allow passing name to client

---

.travis.yml
scripts/prod-cleanup.sh
scripts/prod-prep.sh

hopefully, tweak .gitignore so travis copies the dist dir to live. This
is mostly a test. This code will be replaced with babel compile code
later.

pre & post scripts for travis

---

scripts/prod-prep.sh
src/primus/server.js
test.js

File system calls aren’t working at all. Try another approach to test
if the dist dir is being created & accessible.

Test imported module for travis build

---

scripts/prod-prep.sh

getting things back how they were an hour ago, before git puked

Copy test file into dist

---

src/plugins/combat/spells/Attack.js
src/plugins/combat/spells/BottleToss.js
src/plugins/combat/spells/DeathGlare.js
src/plugins/combat/spells/DrunkenFrenzy.js
src/plugins/combat/spells/GrogDance.js
src/plugins/combat/spells/PirateShanty.js

Bottle Toss, Death Glare, Drunken Frenzy, Grog Dance, Pirate Shanty

Add more spell descs for Pirate

---

src/plugins/players/player.js

If we take more than X attempts to choose a valid next tile, just go
through them all in order & go with the first valid one.
Obviously any more than 8 is pointless. I’ve chosen 5 as an arbitrary
level.
This stops us getting locked in an infinite loop. Given that directions
are weighted, this could (statistically) happen with surprising
frequency. Rough empirical tests suggest we’re taking MORE than 100
attempts roughly 4% of the time.
This may also be responsible for server locks/load, particularly under
high usage.

PickRandomTile lock bug

---

src/primus/server.js

A giant mess of rubbish. Trying to get as much info out of production
as possible, with the fewest PRs. All this junk will be removed
immediately.

test for travis/babel

---

scripts/prod-prep.sh

put full path into prod-prep test

---

scripts/prod-prep.sh

try to check we’re in the right dir

more tweaks

---

src/primus/server.js

dump out more info re src/dist (since heroku is horribly
confused/blind/something)

show a little more info on not found

---

src/shared/logger.js

Just inconsistent with the rest of the project, and very mildly
unclear. No big deal.

trivial code tidy of Logger

---

npm/generate-petdoc.js
package.json

Works on my end. Here's hoping I don't break everything.

Pets Autodoc

---

npm/generate-petdoc.js

This should be *way* more readable. Hopefully.

Improved pet data tables

---

docs/PETS.md
npm/generate-petdoc.js

Mostly just added anchor links to the table of contents so you can click on the name of the pet and go straight to it. Also added [top] anchor links at the end of each pet entry that send you to the top of the page, since it's really long. Got rid of a loop or two and cleaned up the table-making process a little bit.
Looks like your PETS.md is old, anyway. Doesn't include the new pets. Probably my fault for merging an old PETS.md file or something. Anyway, this new one is up-to-date.

Improved pet autodoc again.

---

src/static/settings.js

Add maxPartyMembers setting for party join

Fix party join

---

src/core/base/character.js
src/core/professions/Barbarian.js
src/plugins/combat/battle.js
src/plugins/combat/effect.js
src/plugins/combat/effectmanager.js
src/plugins/combat/effects/Heartbleed.js
src/plugins/combat/effects/LitanyOfPain.js
src/plugins/combat/effects/PercentageHPHeal.js
src/plugins/combat/effects/Poison.js
src/plugins/combat/effects/PoisonedSandwich.js
src/plugins/combat/effects/Thunderstrike.js
src/plugins/combat/effects/Vampire.js
src/plugins/combat/effects/Venom.js
src/plugins/combat/spell.js
src/plugins/combat/spells/Byte.js
src/plugins/combat/spells/DebuffTouch.js
src/plugins/combat/spells/FoodFight.js
src/plugins/combat/spells/Freeleech.js
src/plugins/combat/spells/Siphon.js
src/plugins/combat/spells/Summon.js
src/plugins/combat/spells/Tranquility.js
src/plugins/combat/spelltargetstrategy.js

A whole bunch of bug fixes and reorganization.

Combat fixes

---

src/plugins/combat/effects/Venom.js

I found the note on the Class Balance project and it seemed simple. The lint thingy gave no errors and I ran the server for a while with no problems.
I made everyone level 200 necromancers and looked at a combat log. Everything seems to be working as intended.

venom now based on current hp

---

src/plugins/combat/spells/Summon.js

Necro minions now have their stats recalculated after level adjustment.
Lich minions should now die properly.

Summon fixes

---

src/plugins/combat/spells/FoodFight.js

Food Fight damage has been halved.

Halve food fight damage.

---

src/plugins/events/events/ProfessionChange.js

No more holding on to multiple profession choices. Only one profession choice at a time.

Only one prof choice at a time

---

src/plugins/players/player.movement.js

Reverts IdleLands/IdleLands#501

Revert "Changed drunk movement."

---

src/plugins/combat/battle.js

Track overkill only if target is dead

---

src/plugins/combat/spelltargetpossibilities.js
src/plugins/combat/spelltargetstrategy.js

Flip the Bit now correctly targets living players.

---

src/plugins/players/player.movement.js

If we're going with completely random, would it be better to just pick a number from 0-7 and use that, instead of using weights?

Drunk is now completely random.

---

src/plugins/combat/effects/Poison.js
src/plugins/combat/effects/Vampire.js
src/plugins/combat/effects/Venom.js

Poison's damage formula is now: int * ln(potency+1)/6
Venom and vampire have 1/4 effect on bosses.
Vampire is now based on current hp instead of max hp.

Nerf venom, poison, and vampire. But mostly poison.

---

src/plugins/players/player.js

Gold/xp can't flip sign due to livestats.

---

src/static/settings.ts

Update files for the new soap gender. Thanks to LaundrySoap for the art asset!

Add new base gender

---

src/plugins/combat/spells/_all.js

Intimidate Fix

---

src/core/base/equipment.js
src/shared/stat-calculator.js

The negative version of sentimentality (removes item score).
Adding it as a separate thing because negative sentimentality doesn't always stay that way when vectored.
(New Pull because I forgot a thing. (Thank you Travis))

Adding Vitriol

---

src/core/base/equipment.js
src/shared/stat-calculator.js

Reverts IdleLands/IdleLands#819

Revert "Adding Vitriol"
