- src/plugins/chat/external.chat.irc.js
- src/plugins/chat/sendmessage.socket.js
Puts the player level into the irc chat, by their name. Helpful for
identifying extent of advice required in response to the many ambiguous
questions.
> add player level to irc chat

- primus/server.js
Removed serve-static module (is still used indirectly). Use express
module, with compression module. Removed compression=true flag from
Primus (causes socket problems)
> add compression, remove bad primus flag

- test/client/client.js
allows test client to connect to PORT, otherwise defaults to 8080
> Allow port in test client

- src/plugins/players/player.js
- src/plugins/statistics/statistics.js
- test/client/client.js
Adds “doSave” flag to stats.batchIncrement. Since we do an XP update
right after (both of which save stats by default), the update can save,
not the batch increment.
> Stop player stats saving twice

- index.js
just checks for an .env file at startup. Alerts user and exits if not
found (better than the confusing error messages that otherwise spew out)
> check for env file

- primus/server.js
Hopefully this will force the internal broken game state to be visible
externally, so we can auto-reboot when things are dead.
> return player count externally

- index.js
- src/plugins/events/event.js
- src/primus/server.js
- src/shared/adventure-log.js
- src/shared/data-updater.js
- src/shared/playerlist-updater.js
Move primus dir into src, so we can get rid of babel-register on
production (very slow, not recommended). Also commented out primus
Multiplex (since it’s not used)
> Move primus to /src

- package.json
- src/shared/asset-loader.js
Switched to relative path (so we can transpile from src->dist). Since
not using app-root-path any more, removed it from package.json (did npm
prune & tested. All ok)
> Asset loader use relative path

- src/plugins/events/events/GoldBless.js
- src/plugins/events/events/GoldBlessParty.js
- src/plugins/events/events/GoldForsake.js
- src/plugins/events/events/XPBless.js
- src/plugins/events/events/XPBlessParty.js
- src/plugins/events/events/XPForsake.js
78gold -> 78 gold. 84xp -> 84 xp. Just put a space between quantity and
descriptive, so it’s a little clearer to read (plus consistent with
elsewhere)
> improve bless/forsake event output

- src/primus/server.js
Reads dist/hello.txt - just a dummy file we can get travis to put
there, to test whether our travis deploy is working properly, and will,
for removal of babel-register. Failure is expected return val (until we
de-kink travis)
> Dist test in place for travis deploy

- scripts/prodprep.sh
trim .gitignore so git->heroic will grab the dist directory. For test
(right now) just dump a basic file into /dist. Later, can run babel
command from here too
> Prepare git for deployment of dist

- src/plugins/combat/battle.js
- src/plugins/players/player.js
- src/plugins/statistics/statistics.js
Stop stats saving on every increment (esp bad during battles -
gainXp();gainGold() —> two saves). Default to NOT save on increments.
Manually save during regular saveSteps player save.
> Make statistics save respect saveSteps

- src/plugins/combat/spells/Cure.js
- src/plugins/combat/spelltargetpossibilities.js
- src/plugins/combat/spelltargetstrategy.js
Make Clerics more aggressive (for faster more interesting battles).
Added allyBelowHealthPercent and randomAllyBelowHealthPercent functions
for general use (currently only Cure uses these, but similar could also be used
to attack dying targets etc). 80% cut off is arbitrary, but no point
wasting a round healing someone who’s only 2% sick.
> Clerics only heal health   80%

- src/primus/server.js
forgot that it was pulled into index.js, thus run from the root, not its actual subdir. Didn’t realise how I could test this until just now.
> Point /hello in the right direction 

- scripts/prod-cleanup.sh
- scripts/prod-prep.sh
the copy across is done before this script can run, so changing the
.gitignore has no effect. I suspect we may not need to.
> Simplify prod prep

- scripts/prod-prep.sh
since dist is ignored by .gitignore, it’s likely not created by the
initial clone, therefore we need to create it before we can put
anything in it.
> Create dist dir in container

- src/primus/server.js
Since our rollbar errors are getting close to max for the month
(without paying), on the off chance this is what’s causing those weird
Receiver errors, have commented it out until I’m more actively working
on Travis.
At this point, I’m still mulling possibilities, and focused on other
stuff. Suspect it might be a wandering search engine hitting this end
point & causing problems. Maybe.
> Temp remove /hello

- src/plugins/achievements/achievements/Bossy.js
- src/plugins/achievements/achievements/Boxer.js
- src/plugins/achievements/achievements/Camper.js
- src/plugins/achievements/achievements/Consumerist.js
- src/plugins/achievements/achievements/Critical.js
- src/plugins/achievements/achievements/DigitalMagician.js
- src/plugins/achievements/achievements/Drunk.js
- src/plugins/achievements/achievements/Effective.js
- src/plugins/achievements/achievements/Eventful.js
- src/plugins/achievements/achievements/Explorative.js
- src/plugins/achievements/achievements/Golden.js
- src/plugins/achievements/achievements/Levelable.js
- src/plugins/achievements/achievements/PKer.js
- src/plugins/achievements/achievements/Slayer.js
- src/plugins/achievements/achievements/SoleFoot.js
- src/plugins/achievements/achievements/Soloer.js
- src/plugins/achievements/achievements/Sponge.js
- src/plugins/achievements/achievements/Territorial.js
- src/plugins/achievements/achievements/Unstoppable.js
- src/plugins/achievements/achievements/Walker.js
used .toLocaleString() to insert commas (or fullstops in parts of
europe) to any large numbers in the achievements text.
We CAN force locales with this, but it’s not supported in all browsers.
This will default to something vaguely sensible, and appears to be well
supported:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global
_Objects/Number/toLocaleString#Browser_compatibility
> Make achievement text easier to read

- src/core/base/character.js
Generator already does the concat one. It’s not going to change mid
game. No point doing 3x concats for every single stat retrieval.
Is debatable whether a const in the top of this file would be more
efficient than referencing the entire Generator class. Likely sub
optimal to have the same code in two places though.
> Stop char stats proxy concatenating 3 lists every time a stat is read

- src/plugins/players/player.js
- src/plugins/players/player.movement.js
Replaces with previous fix with far better solution suggested by Anexes
(and helped by therealtahu).
Removes each weight from the possible choices, thus no re-choosing
invalid tiles, and a max of 8 loops possible. Should be MUCH faster
than my earlier solution, and faster than original.
Plus, no lock ups.
> improve pickRandomTile lock bug

- src/plugins/players/player.js
- src/plugins/players/player.movement.js
Off by one error. Checking for “player surrounded by 8 non-valid tiles”
in the wrong position.
> don't log non errors in pickRandomTile

- src/core/game-state.js
In fast login/out situations, we can end up with multiple timeouts set per player.
If it exists, clear the previous one, rather than leaving it running & losing the id.
Should help with players inadvertently being logged out (and thus seeing the “welcome back” message).
> replace not overwrite player timeouts

- src/plugins/combat/battle.socket.js
- src/plugins/gm/teleport.socket.js
- src/plugins/gm/toggleachievement.socket.js
- src/plugins/gm/togglemode.socket.js
- src/plugins/pets/pet.attr.socket.js
- src/plugins/pets/pet.buy.socket.js
- src/plugins/pets/pet.equipment.unequip.socket.js
- src/plugins/pets/pet.feed.socket.js
- src/plugins/pets/pet.inventory.equip.socket.js
- src/plugins/pets/pet.inventory.sell.socket.js
- src/plugins/pets/pet.profession.socket.js
- src/plugins/pets/pet.smart.socket.js
- src/plugins/pets/pet.swap.socket.js
- src/plugins/pets/pet.takeGold.socket.js
- src/plugins/pets/pet.upgrade.socket.js
- src/plugins/players/player.choice.socket.js
- src/plugins/players/player.gender.socket.js
- src/plugins/players/player.personality.socket.js
- src/plugins/players/player.title.socket.js
In fast log in/out situations, we can get delayed/lagged or confused messages from the client. This results in us trying to find a player that doesn’t exist in our official list (i.e., we’ve already logged them out & removed them from gamestate.players).
Just stop the whole thing puking. Throw out the client message.
> if player has logged out, won't be in gamestate list

- scripts/prod-prep.sh
- src/primus/server.js
for whatever reason, heroku is saying /test.js doesn’t exist (it’s in the repo - not copying across? who knows). Just go full into the official babel test instead.
> work around silly heroku issue

- scripts/prod-prep.sh
(this should - I would have thought - have been pulled in with the rest of the node_modules, but apparently not). Slowly slowly.
> get babel installed before use

- scripts/prod-prep.sh
For some reason, our app can’t see files that have been placed there by the heroku startup process. Maybe permissioning? Hopefully this will show us
> check permissioning

- src/plugins/combat/effects/Vampire.js
move casterLive decl above where it’s needed.
> fix vampire undeclared var bug

- src/plugins/events/events/XPForsake.js
It was displaying the amount of xp before it was modified by personalities, so I updated it to be like XPBless. I put Math.abs(xpMod) in the event text rather than just xpMod, to hopefully change as little as possible on the surface.
> Fixed XPForsake event text

- src/core/emitter-watchers.js
- src/plugins/players/player.login.socket.js
- src/primus/server.js
Updates the player after primus adds the new socket, not after.
Also fix a scoping issue with primus.delPlayer()
> Fixes semi-login

- src/plugins/combat/battle.js
- src/plugins/party/party.js
Unfortunately my last PR only checked for players' levels, but still divided by all the total number of party members when calculating party level.
I fixed `Party.level` so it gives an accurate party level, but I had to put in an if to check if the leader was human, so non-player parties can still calculate their level.
I also removed `get winners()` and `get losers()` from battle.js, added `get losingTeam()`, then used `this.losingTeam.level` and `this.winningTeam.level` instead of using `this.winners` and `this.losers` to calculate the parties' levels. Should make `endBattleBonuses()` a tad easier to read, and this way any changes that need to be made to party level calculations can be done in `Party.level`
I was gone for most of today and when I got back it seemed like nobody was …
> Actually fix battle xp this time

- src/core/professions/Lich.js
- src/plugins/combat/battle.js
- src/plugins/combat/spells/Bonecraft.js
- src/plugins/combat/spells/Summon.js
- src/plugins/combat/spelltargetpossibilities.js
- src/plugins/combat/spelltargetstrategy.js
* Summons now use their death message. Closes #478
* Summons correctly remove themselves from the party if their summoner gets Bonecrafted. Closes #474
* Bonecraft now tracks the original party, not the previous one. Closes #479
* Fix a bug where bonecrafting an entire party and then killing the last summon would break battle rewards.
* Battle debug no longer exits when a Lich is killed.
> Fix several necromancer bugs

- src/plugins/events/events/BattleBoss.js
- src/shared/monster-generator.js
Rather than their actual names, bosses still seem to use their party name (if they have one,) in combat logs. Therefore, they still return with Character.BossKills.Wardens (for example,) but it does go through and increment once for each boss. Now all that's left is to fix it so they use their actual names rather than their party names.
> Upon beating boss party, return boss names rather than boss party name.

- src/plugins/combat/battle.js
I was looking through the recent changes and noticed that both healing given and healing received were being incremented for the same person ("source.") I changed it so healing received is incremented for the "target."
> Fix healing received statistic

- src/plugins/combat/effects/Venom.js
Tahu mentioned that current hp has a getter and that it would be better to use that than to directly access __current. It passed the lint thing and everything worked as intended on the test server.
> use hp getter instead of __current for venom

- src/plugins/combat/spells/AntimagicArrow.js
- src/plugins/combat/spells/Summon.js
Dracoliches no longer mirror players. Instead, they always spawn as liches. Raised slot cost from 2 to 4.
Demogorgons now mirror players. Raised slot cost from 4 to 6.
Antimagic Arrow's mp reduction has been floored, so mp should only be reduced by whole numbers now.
> Changed summon spell & floored Antimagic Arrow mp reduction

- src/core/professions/Archer.js
- src/plugins/combat/spells/AntimagicArrow.js
- src/plugins/combat/spells/Multishot.js
- src/plugins/combat/spells/Shattershot.js
This is an attempt to balance archers. Feedback welcome.
Archer hp/con reduced from 5 to 3, archer hp/dex reduced from 3 to 1.
Shattershot damage greatly reduced. Scales with str and dex, but favors str.
Antimagic Arrow damage greatly reduced. Scales with int and dex, but favors int.
Multishot damage greatly reduced. Spellpower now only benefits number of shots, not damage.
> Archer tweaks.

- src/plugins/players/player.movement.js
Drunk movement now considers previous movement direction.
I also changed the drunk weights to a simple, hard-coded array that favors forward movement (to a degree,) but is otherwise largely normalized.
I can't see the players on the map to see if they're moving as intended, but everything ran fine, so I don't see why they wouldn't be.
> Fixed and changed drunk movement.

- src/plugins/combat/spells/SweepingGeneralization.js
Sweeping Generalization damage has been halved.
> Halve sweeping gen. damage.

- src/plugins/combat/spells/FlipTheBit.js
- src/plugins/combat/spelltargetpossibilities.js
- src/plugins/combat/spelltargetstrategy.js
- src/shared/monster-generator.js
Added targetting functions in spelltargetpossibilities and spelltargetstrategy for Flip the Bit, that rejects bosses as well as bitomancers.
Boss party bosses weren't being flagged as bosses (`$isBoss`) during creation. As such, I expect they were affected by DebuffTouch and stuns like a normal enemy. If this was desired behavior, let me know, it won't take long to fix. This PR flags all boss party bosses as such, so they should no longer be affected by stuns, targeted by FlipTheBit, or damaged directly by DebuffTouch.
> Can't Flip the Bit on bosses, boss party bosses flagged as bosses.

- src/plugins/premium/perks.js
festival code is not well designed to handle giving added effects over multiplicative ones, so the effects festival is being modified since the current values are broken.
> Update perks.js (#797)

- src/shared/regions.js
Certain regions or locations require collectibles to access and parties forming there can get players stuck
> Prevent party formation in some regions
